language: node_js

node_js:
  - 7
  - 6

before_install:
  - npm -g i npm@latest

before_script:
  - npm -g i gulp-cli jest-cli ; npm beckend/cmd-spawn

script:
  - gulp ci

sudo: false

notifications:
  email: false
